export interface IReservation {
    firstName: string,
    reservationId : number,
    locationId: number,
    roomId : number,
    roomName: string | undefined,
    customerId : number,
    arrivalDate: Date     // "YYYY-MM-DD",
    departureDate: Date     // "YYYY-MM-DD",
    reservationDate: Date     // "YYYY-MM-DD HH:MM:SS",
    totalPrice: number,
    status: 'CONFIRM' | 'CHECKED-IN' | 'CHECKED-OUT',
    paidAmount : number,
    dueAmount : number,
    numberOfGuest : number,
}
